name: 'retail_analytics_dbt'
version: '1.0.0'
config-version: 2

profile: 'retail_analytics_dbt'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

docs-paths: ["docs"]

vars:
  start_date: '2012-01-01'
  end_date: '2015-12-31'

models:
  retail_analytics_dbt:
    # Couche Bronze - Données brutes depuis Azure
    bronze:
      +materialized: incremental
      +schema: bronze
      +tags: ["bronze", "raw"]
      +on_schema_change: "fail"
    
    # Couche Silver - Nettoyage et validation
    silver:
      +materialized: table
      +schema: silver
      +tags: ["silver", "cleaned"]
    
    # Couche Gold - Star Schema
    gold:
      +materialized: table
      +schema: gold
      +tags: ["gold", "production"]
      
      dimensions:
        +tags: ["dimension"]
      
      faits:
        +tags: ["fact"] 
    
    analytics:
        +materialized: view
        +schema: analytics
        +tags: ["analytics", "reporting"]

seeds:
  retail_analytics:
    +schema: seeds
    +quote_columns: false

snapshots:
  retail_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: _loaded_at

tests:
  retail_analytics:
    +store_failures: true
    +schema: test_failures